iStore/Areas/Admin/Controllers/DanhGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace iStore.Areas.Admin.Controllers
{
    public class DanhGiaController : Controller
    {
        // GET: Admin/DanhGia
        public ActionResult Index()
        {
            return View();
        }
    }
}

iStore/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="~/Assets/Admin/css/styles.css">
    <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet" />
</head>
<body>
    <div class="wrapper">
        <aside id="sidebar">
            <div class="d-flex">
                <button class="toggle-btn" type="button">
                    <i class="lni lni-grid-alt"></i>
                </button>
                <div class="sidebar-logo">
                    <a href="#" class="fs-2">iStore</a>
                </div>
            </div>



            <ul class="sidebar-nav">
                <li class="sidebar-item">
                    <a href="@Url.Action("Index", "Home", new { area = "Admin" })" class="sidebar-link">
                        <i class="lni lni-dashboard"></i>
                        <span>Trang chủ</span>
                    </a>
                </li>



                <li class="sidebar-item">
                    <a href="@Url.Action("Index", "DanhMuc", new { area = "Admin" })" class="sidebar-link">
                        <i class="lni lni-users"></i>
                        <span>Danh mục</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a href="@Url.Action("Index", "SanPham", new { area = "Admin" })" class="sidebar-link">
                        <i class="lni lni-users"></i>
                        <span>Sản phẩm</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a href="@Url.Action("Index", "ThanhToan", new { area = "Admin" })" class="sidebar-link">
                        <i class="lni lni-users"></i>
                        <span>Thanh toán</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a href="@Url.Action("Index", "DonHang", new { area = "Admin" })" class="sidebar-link">
                        <i class="lni lni-users"></i>
                        <span>Đơn hàng</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a href="@Url.Action("Index", "KhachHang", new { area = "Admin" })" class="sidebar-link">
                        <i class="lni lni-users"></i>
                        <span>Khách hàng</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a href="@Url.Action("Index", "MaGiamGia", new { area = "Admin" })" class="sidebar-link">
                        <i class="lni lni-users"></i>
                        <span>Mã giảm giá</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a href="@Url.Action("Index", "DanhGia", new { area = "Admin" })" class="sidebar-link">
                        <i class="lni lni-users"></i>
                        <span>Đánh giá</span>
                    </a>
                </li>



                <li class="sidebar-item">
                    <a href="#" class="sidebar-link collapsed has-dropdown" data-bs-toggle="collapse"
                       data-bs-target="#product" aria-expanded="false" aria-controls="product">
                        <i class="lni lni-laptop-phone"></i>
                        <span>Quản lý sản phẩm</span>
                    </a>
                    <ul id="product" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                        <li class="sidebar-item">
                            <a href="@Url.Action("Index", "Products", new { area = "Admin" })" class="sidebar-link">Sản phẩm</a>
                        </li>
                        <li class="sidebar-item">
                            <a href="@Url.Action("Index", "CategoryBrands", new { area = "Admin" })" class="sidebar-link">Danh mục - Thương hiệu</a>
                        </li>
                    </ul>
                </li>

            </ul>

            <div class="sidebar-footer">
                <a href="@Url.Action("Index", "DangXuat", new { area = "Admin" })" class="sidebar-link">
                    <i class="lni lni-exit"></i>
                    <span>Đăng xuất</span>
                </a>
            </div>
        </aside>
        <div class="main p-3">
            @RenderBody()
        </div>
    </div>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Assets/Admin/js/JavaScript.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>